services:
  astro:
    image: node:20-alpine
    container_name: astro-dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:4321"
    command: sh -c "npm install && npx astro dev --host"